-define(ACCEPT_TIMEOUT, clusterl_config:value(accept_timeout)).
-define(BROADCAST_IP, clusterl_config:value(broadcast_ip)).
-define(CONNECT_TIMEOUT, clusterl_config:value(connect_timeout)).
-define(ID, clusterl_config:value(id)).
-define(RADIO_PORT, clusterl_config:value(radio_port)).
